import { PART_CATALOGS, PartCatalog, SubCatalog } from '@/lib/constants/part-catalogs';

/**
 * Get catalog definition by code
 */
export function getCatalogByCode(code: string): PartCatalog | undefined {
  return PART_CATALOGS.find((c) => c.code === code);
}

/**
 * Get sub-catalog definition by catalog and sub-catalog code
 */
export function getSubCatalogByCode(catalogCode: string, subCatalogCode: string): SubCatalog | undefined {
  const catalog = getCatalogByCode(catalogCode);
  return catalog?.subCatalogs.find((s) => s.code === subCatalogCode);
}

/**
 * Validate attributes for a catalog
 * Returns an array of missing required attribute keys
 */
export function validateCatalogAttributes(
  catalogCode: string,
  attributes: Record<string, any>
): string[] {
  const catalog = getCatalogByCode(catalogCode);
  if (!catalog) return [];

  const missingKeys: string[] = [];
  // Note: details in PART_CATALOGS are display names. 
  // We might want to normalize them to keys (lowercase, underscores) for actual storage.
  // For now, checking if keys exist corresponding to the detail names.
  
  for (const detail of catalog.details) {
    // Simple normalization strategy: lowercase and remove special chars for key matching if needed
    // But for now assuming the attribute keys should match the display names or we should have a mapping.
    // Given the CSV, let's assume keys are close to display names.
    // Let's just check if the key exists in some form? 
    // Or strictly: keys in attributes should match the Detail names?
    
    // If attributes is empty and catalog has details, that's a validation error if we enforce it.
    // But the schema says optional attributes.
  }
  
  return missingKeys;
}

/**
 * Generate a QIP based on the preferred format: QIP-[CAT]-[Sub-Cat]-[Number]
 * Note: The Number part usually needs to be generated by the database sequence or logic.
 * This function just generates the prefix.
 */
export function generateQipPrefix(catalogCode: string, subCatalogCode: string): string {
  return `QIP-${catalogCode}-${subCatalogCode}`;
}

/**
 * Normalize attribute key from display name
 * e.g. "Pressure Rating" -> "pressure_rating"
 */
export function normalizeAttributeKey(displayName: string): string {
  return displayName.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

